use_frameworks!

platform :ios, '9.0'

target 'YKPersonalPod_Example' do
  pod 'YKPersonalPod', :path => '../'

  target 'YKPersonalPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
